package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name="application")
public class Application implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer applicationId;
	
	private int userId;
	private int positionId;
	private String firstName;
	private String lastName;
	private String contactEmail;
	private String phone;
	private String address;
	private String city;
	private String state;
	private int zipcode;
	private String country;
	private String resumePath;
	private String workBeginDate;
	private String applicantWebsite;
	private String status;
	private Date applicationTime;

	public Application() {
	}

	public Application(int userId, int positionId, String firstName, String lastName, String contactEmail, String phone,
			String address, String city, String state, int zipcode, String country, String status,
			Date applicationTime) {
		this.userId = userId;
		this.positionId = positionId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.contactEmail = contactEmail;
		this.phone = phone;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.status = status;
		this.applicationTime = applicationTime;
	}

	public Application(int userId, int positionId, String firstName, String lastName, String contactEmail, String phone,
			String address, String city, String state, int zipcode, String country, String resumePath,
			String workBeginDate, String applicantWebsite, String status, Date applicationTime) {
		this.userId = userId;
		this.positionId = positionId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.contactEmail = contactEmail;
		this.phone = phone;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.resumePath = resumePath;
		this.workBeginDate = workBeginDate;
		this.applicantWebsite = applicantWebsite;
		this.status = status;
		this.applicationTime = applicationTime;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(int zipcode) {
		this.zipcode = zipcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getResumePath() {
		return this.resumePath;
	}

	public void setResumePath(String resumePath) {
		this.resumePath = resumePath;
	}

	public String getWorkBeginDate() {
		return this.workBeginDate;
	}

	public void setWorkBeginDate(String workBeginDate) {
		this.workBeginDate = workBeginDate;
	}

	public String getApplicantWebsite() {
		return this.applicantWebsite;
	}

	public void setApplicantWebsite(String applicantWebsite) {
		this.applicantWebsite = applicantWebsite;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getApplicationTime() {
		return this.applicationTime;
	}

	public void setApplicationTime(Date applicationTime) {
		this.applicationTime = applicationTime;
	}

}
