package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * EduBackground generated by hbm2java
 */
public class EduBackground implements java.io.Serializable {

	private Integer eduBgId;
	private int profileId;
	private String university;
	private String degree;
	private String major;
	private String activity;
	private Date fromYear;
	private Date toYear;
	private String description;

	public EduBackground() {
	}

	public EduBackground(int profileId, String university, String degree, String major, String activity, Date fromYear,
			Date toYear) {
		this.profileId = profileId;
		this.university = university;
		this.degree = degree;
		this.major = major;
		this.activity = activity;
		this.fromYear = fromYear;
		this.toYear = toYear;
	}

	public EduBackground(int profileId, String university, String degree, String major, String activity, Date fromYear,
			Date toYear, String description) {
		this.profileId = profileId;
		this.university = university;
		this.degree = degree;
		this.major = major;
		this.activity = activity;
		this.fromYear = fromYear;
		this.toYear = toYear;
		this.description = description;
	}

	public Integer getEduBgId() {
		return this.eduBgId;
	}

	public void setEduBgId(Integer eduBgId) {
		this.eduBgId = eduBgId;
	}

	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	public Date getFromYear() {
		return this.fromYear;
	}

	public void setFromYear(Date fromYear) {
		this.fromYear = fromYear;
	}

	public Date getToYear() {
		return this.toYear;
	}

	public void setToYear(Date toYear) {
		this.toYear = toYear;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
