package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EduBackground generated by hbm2java
 */
@Entity
@Table(name="edu_background")
public class EduBackground implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer eduBgId;
	
	@Column(name="university")
	private String university;
	private String degree;
	private String major;
	private String activity;
	private String fromYear;
	private String toYear;
	private String description;

	@ManyToOne(optional = false)
	@JoinColumn(name="profileId")
	private Profile profile;
	
	public EduBackground() {
	}

	public Integer getEduBgId() {
		return this.eduBgId;
	}

	public void setEduBgId(Integer eduBgId) {
		this.eduBgId = eduBgId;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	public String getFromYear() {
		return this.fromYear;
	}

	public void setFromYear(String fromYear) {
		this.fromYear = fromYear;
	}

	public String getToYear() {
		return this.toYear;
	}

	public void setToYear(String toYear) {
		this.toYear = toYear;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

}
