package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * Experience generated by hbm2java
 */
public class Experience implements java.io.Serializable {

	private Integer experId;
	private int profileId;
	private String title;
	private String company;
	private String location;
	private Date fromDate;
	private Date toDate;
	private String description;

	public Experience() {
	}

	public Experience(int profileId, String title, String company, String location, Date fromDate, Date toDate) {
		this.profileId = profileId;
		this.title = title;
		this.company = company;
		this.location = location;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public Experience(int profileId, String title, String company, String location, Date fromDate, Date toDate,
			String description) {
		this.profileId = profileId;
		this.title = title;
		this.company = company;
		this.location = location;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.description = description;
	}

	public Integer getExperId() {
		return this.experId;
	}

	public void setExperId(Integer experId) {
		this.experId = experId;
	}

	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
