package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name="experience")
public class Experience implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer experId;
	
	@Column(name="title")
	private String title;
	private String company;
	private String location;
	private Date fromDate;
	private Date toDate;
	private String description;
	
	@ManyToOne(optional = false,cascade = CascadeType.ALL)
	@JoinColumn(name="profileId")
	private Profile profile;

	public Experience() {
	}

	public Experience(int profileId, String title, String company, String location, Date fromDate, Date toDate) {
		this.title = title;
		this.company = company;
		this.location = location;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public Experience(int profileId, String title, String company, String location, Date fromDate, Date toDate,
			String description) {
		this.title = title;
		this.company = company;
		this.location = location;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.description = description;
	}

	public Integer getExperId() {
		return this.experId;
	}

	public void setExperId(Integer experId) {
		this.experId = experId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}
	
}
