package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

	private Integer feedbackId;
	private int applicationId;
	private String result;
	private String interviewTime;
	private String interviewLocation;
	private String comments;

	public Feedback() {
	}

	public Feedback(int applicationId) {
		this.applicationId = applicationId;
	}

	public Feedback(int applicationId, String result, String interviewTime, String interviewLocation, String comments) {
		this.applicationId = applicationId;
		this.result = result;
		this.interviewTime = interviewTime;
		this.interviewLocation = interviewLocation;
		this.comments = comments;
	}

	public Integer getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(Integer feedbackId) {
		this.feedbackId = feedbackId;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getInterviewTime() {
		return this.interviewTime;
	}

	public void setInterviewTime(String interviewTime) {
		this.interviewTime = interviewTime;
	}

	public String getInterviewLocation() {
		return this.interviewLocation;
	}

	public void setInterviewLocation(String interviewLocation) {
		this.interviewLocation = interviewLocation;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
