package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name="profile")
public class Profile implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer profileId;
	
	@Column(name="firstName")
	private String firstName;
	private String lastName;
	private String Headline;
	private String email;
	private String phone;
	private String address;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String summary;
	private String portraitPath;
	
	@Transient
	private CommonsMultipartFile portrait;
	
	@OneToOne(mappedBy="profile")
	private IndividualAccount individualAccount;

	@OneToMany(cascade = CascadeType.ALL, mappedBy="profile")
	@OrderBy("fromDate DESC")
	private List<Experience> experiences;
	
	@OneToMany(cascade = CascadeType.ALL, mappedBy="profile")
	@OrderBy("fromYear DESC")
	private List<EduBackground> educations;
	
	@OneToMany(cascade = CascadeType.ALL, mappedBy="profile")
	private List<Skill> skills;
	
	public Profile() {
	}

	public Profile(String portraitPath) {
		this.portraitPath = portraitPath;
	}

	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getHeadline() {
		return Headline;
	}

	public void setHeadline(String headline) {
		Headline = headline;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getPortraitPath() {
		return this.portraitPath;
	}

	public void setPortraitPath(String portraitPath) {
		this.portraitPath = portraitPath;
	}

	public IndividualAccount getIndividualAccount() {
		return individualAccount;
	}

	public void setIndividualAccount(IndividualAccount individualAccount) {
		this.individualAccount = individualAccount;
	}

	public CommonsMultipartFile getPortrait() {
		return portrait;
	}

	public void setPortrait(CommonsMultipartFile portrait) {
		this.portrait = portrait;
	}

	public List<Experience> getExperiences() {
		return experiences;
	}

	public void setExperiences(List<Experience> experiences) {
		this.experiences = experiences;
	}

	public List<EduBackground> getEducations() {
		return educations;
	}

	public void setEducations(List<EduBackground> educations) {
		this.educations = educations;
	}

	public List<Skill> getSkills() {
		return skills;
	}

	public void setSkills(List<Skill> skills) {
		this.skills = skills;
	}

}
