package com.xdong.model;
// Generated 2020-3-28 16:14:24 by Hibernate Tools 5.4.12.Final

/**
 * Skills generated by hbm2java
 */
public class Skills implements java.io.Serializable {

	private Integer skillsId;
	private int profileId;
	private String skillsContent;

	public Skills() {
	}

	public Skills(int profileId, String skillsContent) {
		this.profileId = profileId;
		this.skillsContent = skillsContent;
	}

	public Integer getSkillsId() {
		return this.skillsId;
	}

	public void setSkillsId(Integer skillsId) {
		this.skillsId = skillsId;
	}

	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	public String getSkillsContent() {
		return this.skillsContent;
	}

	public void setSkillsContent(String skillsContent) {
		this.skillsContent = skillsContent;
	}

}
